# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='书名')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='简介')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='再次更新时间')),
                ('pv', models.PositiveIntegerField(default=1)),
                ('uv', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': '图书列表',
                'verbose_name_plural': '图书列表',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_nav', models.BooleanField(default=False, verbose_name='是否导航')),
            ],
            options={
                'verbose_name': '小说分类',
                'verbose_name_plural': '小说分类',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Category', verbose_name='分类'),
        ),
    ]
