# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters', models.CharField(max_length=50, verbose_name='章节名称')),
                ('content', models.TextField(help_text='内容为markdown格式', verbose_name='正文')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Book', verbose_name='目标图书')),
            ],
            options={
                'verbose_name': '章节内容',
                'verbose_name_plural': '章节内容',
            },
        ),
    ]
