# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novel', '0001_initial'),
        ('chapter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000, verbose_name='评论内容')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Book', verbose_name='评论小说')),
                ('comment_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.Chapter', verbose_name='评论章节')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
